version: 2
updates:
  # Fetch and update latest `npm` packages
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '00:00'
    open-pull-requests-limit: 10
    reviewers:
      - mtdvlpr
    assignees:
      - mtdvlpr
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope

  # Fetch and update latest `github-actions` packages
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
      time: '00:00'
    open-pull-requests-limit: 10
    reviewers:
      - mtdvlpr
    assignees:
      - mtdvlpr
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope
